name: ClimaBot - Twitter

on:
  schedule:
    - cron: '*/6 * * * *' 

jobs:
  run_bot_realtime:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Realtime Weather
        run: python realtime_weather.py
        env:
          API_KEY_WEATHER: ${{ secrets.API_KEY_WEATHER }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN}}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}